spring.datasource.url=jdbc:mysql://localhost:3306/classhub_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=classhub_user
spring.datasource.password=ClassHub@2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false

server.port=8080

# JWT
jwt.secret=classhub-super-secret-key-2026-do-an-tot-nghiep-spring-boot-flutter
jwt.expiration=86400000

# Lombok
spring.main.allow-bean-definition-overriding=true

# VietQR — Template cho QR code
vietqr.template=compact2

# VietQR — Thông tin tài khoản cố định (KHÔNG DÙNG NỮA - đã chuyển sang DB)
# Bank BIN: MB=970422 | VCB=970436 | TCB=970407 | ACB=970416 | VPB=970432
# vietqr.bank-bin=970415
# vietqr.account-no=109875610620
# vietqr.account-name=Nguyen Duy Phonggg